// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWM1skxCJkGC_bWPe5QBvKgRDwODJgBQQ',
    appId: '1:637216558287:web:549f9d176a13105c2ebbba',
    messagingSenderId: '637216558287',
    projectId: 'unbaiq-trion-customer-app',
    authDomain: 'unbaiq-trion-customer-app.firebaseapp.com',
    databaseURL: 'https://unbaiq-trion-customer-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unbaiq-trion-customer-app.firebasestorage.app',
    measurementId: 'G-H8D0ETFZ79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-mG8I-eUPENHE_n3H1lmTa3k-trktmo',
    appId: '1:637216558287:android:cf5516e911b978232ebbba',
    messagingSenderId: '637216558287',
    projectId: 'unbaiq-trion-customer-app',
    databaseURL: 'https://unbaiq-trion-customer-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unbaiq-trion-customer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDavBENuZuZAAr6ZERhrLOY9_86Wq37XBI',
    appId: '1:637216558287:ios:b2eda098a44132d32ebbba',
    messagingSenderId: '637216558287',
    projectId: 'unbaiq-trion-customer-app',
    databaseURL: 'https://unbaiq-trion-customer-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unbaiq-trion-customer-app.firebasestorage.app',
    iosBundleId: 'com.stafftally.staff',
  );
}
